import type { Character as CharacterDB } from "genshin-db";

import type { ElementName } from "../elements";

export const CharacterNames = {
  AETHER: "Итэр",
  AINO: "Айно",
  ALBEDO: "Альбедо",
  ALHAITHAM: "Аль-Хайтам",
  ARATAKI_ITTO: "Итто",
  ARLECCHINO: "Арлекино",
  BAIZHU: "Бай Чжу",
  BARBARA: "Барбара",
  BEIDOU: "Бэй Доу",
  BENNETT: "Беннет",
  CANDACE: "Кандакия",
  CHEVREUSE: "Шеврёз",
  CLORINDE: "Клоринда",
  COLLEI: "Коллеи",
  DAHLIA: "Далия",
  DEHYA: "Дэхья",
  DILUC: "Дилюк",
  DIONA: "Диона",
  DORI: "Дори",
  DURIN: "Дурин",
  FISCHL: "Фишль",
  FURINA: "Фурина",
  GAMING: "Ка Мин",
  GANYU: "Гань Юй",
  GOROU: "Горо",
  IANSAN: "Иансан",
  IFA: "Ифа",
  INEFFA: "Инеффа",
  JAHODA: "Ягода",
  JEAN: "Джинн",
  KACHINA: "Качина",
  KAEDEHARA_KAZUHA: "Кадзуха",
  KAEYA: "Кэйа",
  KAMISATO_AYAKA: "Аяка",
  KAMISATO_AYATO: "Аято",
  KAVEH: "Кавех",
  KEQING: "Кэ Цин",
  KINICH: "Кинич",
  KIRARA: "Кирара",
  KLEE: "Кли",
  LAN_YAN: "Лань Янь",
  LAUMA: "Лаума",
  LAYLA: "Лайла",
  LISA: "Лиза",
  LUMINE: "Люмин",
  LYNETTE: "Линетт",
  LYNEY: "Лини",
  MANEKIN: "Манекен (м)",
  MANEKINA: "Манекен (ж)",
  MAVUIKA: "Мавуика",
  MIKA: "Мика",
  MONA: "Мона",
  MUALANI: "Муалани",
  NAHIDA: "Нахида",
  NAVIA: "Навия",
  NEFER: "Нефер",
  NEUVILLETTE: "Нёвиллет",
  NILOU: "Нилу",
  SANGONOMIYA_KOKOMI: "Кокоми",
  VARESA: "Вареса",
  VENTI: "Венти",
  XIANYUN: "Сянь Юнь",
  XINGQIU: "Син Цю",
  YELAN: "Е Лань",
  YOIMIYA: "Ёимия",
  YUMEMIZUKI_MIZUKI: "Мидзуки",
} as const;

export type CharacterName = typeof CharacterNames[keyof typeof CharacterNames];

export interface Character extends Omit<CharacterDB, "stats"> {
  elementText: ElementName | "Нет";
  name: CharacterName;
}
