import {
  createEntityAdapter,
  createSelector,
  createSlice,
  type SliceCaseReducers,
  type SliceSelectors,
} from "@reduxjs/toolkit";

import { type VideoSource, type VideoSourceId, VideoSourceIds } from "@/types/video-sources.types";

export const videoSourcesAdapter = createEntityAdapter<VideoSource>({
  sortComparer: (a, b) => {
    const aDateTime = new Date(a.date).getTime();
    const bDateTime = new Date(b.date).getTime();

    return aDateTime === bDateTime ? a.title.localeCompare(b.title) : bDateTime - aDateTime;
  },
});

const initialState = videoSourcesAdapter.getInitialState(undefined, {
  [VideoSourceIds.ALL_ABOUT_ALL_ARTIFACT_SETS_2023]: {
    id: VideoSourceIds.ALL_ABOUT_ALL_ARTIFACT_SETS_2023,
    author: "Miron MinMax",
    title: "ВСЁ про ВСЕ сеты АРТЕФАКТОВ! ft. @AnimeCool_Genshin",
    date: "2023-12-31",
    vkvideo: "https://vkvideo.ru/video-227044935_456239083",
    youtube: "https://youtu.be/kCu0ux0hUCg",
  },
  [VideoSourceIds.ALL_ABOUT_ALL_ARTIFACT_SETS_2025]: {
    id: VideoSourceIds.ALL_ABOUT_ALL_ARTIFACT_SETS_2025,
    author: "Miron MinMax",
    title: "ВСЁ про ВСЕ Сеты Артефактов | Тир-лист | 2025",
    date: "2025-11-30",
    vkvideo: "https://vkvideo.ru/video-227044935_456239276",
    youtube: "https://youtu.be/TaDugsj9U5c",
  },
  [VideoSourceIds.ALL_ABOUT_ALL_TALENTS]: {
    id: VideoSourceIds.ALL_ABOUT_ALL_TALENTS,
    author: "Miron MinMax",
    title: "ВСЁ про ВСЕ таланты ft.@AnimeCool_Genshin",
    date: "2024-01-19",
    vkvideo: "https://vkvideo.ru/video-227044935_456239080",
    youtube: "https://youtu.be/UQpDXX2Umyk",
  },
  [VideoSourceIds.FIRST_CONSTELLATION_OR_SIGNATURE_WEAPON]: {
    id: VideoSourceIds.FIRST_CONSTELLATION_OR_SIGNATURE_WEAPON,
    author: "Miron MinMax",
    title: "С1 или Сигна? Что Лучше и Насколько? | Про Всех 5★ Персонажей",
    date: "2025-01-15",
    vkvideo: "https://vkvideo.ru/video-227044935_456239189",
    youtube: "https://youtu.be/NfgsESKwsdk",
  },
  [VideoSourceIds.GUIDE_TO_A_DAY_CARVED_FROM_RISING_WINDS_AND_AUBADE_OF_MORNINGSTAR_AND_MOON_IN_6_3]: {
    id: VideoSourceIds.GUIDE_TO_A_DAY_CARVED_FROM_RISING_WINDS_AND_AUBADE_OF_MORNINGSTAR_AND_MOON_IN_6_3,
    author: "Miron MinMax",
    title: "Нужны ли Новые Сеты? | Сравнение на Всех Носителях [Genshin Impact 6.3]",
    date: "2026-01-10",
    vkvideo: "https://vkvideo.ru/video-227044935_456239286",
    youtube: "https://youtu.be/wV4ECCI6Oso",
  },
  [VideoSourceIds.GUIDE_TO_AINO_IN_6_0]: {
    id: VideoSourceIds.GUIDE_TO_AINO_IN_6_0,
    author: "Анимекул",
    title: "Зачем нужна Айно? | Подробный гайд на Айно [Genshin Impact 6.0]",
    date: "2025-09-11",
    vkvideo: "https://vkvideo.ru/video-231668223_456239064",
    youtube: "https://youtu.be/u-bzTR12UuA",
  },
  [VideoSourceIds.GUIDE_TO_ARLECCHINO_IN_5_3]: {
    id: VideoSourceIds.GUIDE_TO_ARLECCHINO_IN_5_3,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Арлекино в 5.3",
    date: "2025-01-22",
    vkvideo: "https://vkvideo.ru/video-227044935_456239191",
    youtube: "https://youtu.be/VY0Kt2AaMGY",
  },
  [VideoSourceIds.GUIDE_TO_CHASCA_IN_5_8]: {
    id: VideoSourceIds.GUIDE_TO_CHASCA_IN_5_8,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Часку в 5.8",
    date: "2025-08-22",
    vkvideo: "https://vkvideo.ru/video-227044935_456239250",
    youtube: "https://youtu.be/OmSwenN-e8s",
  },
  [VideoSourceIds.GUIDE_TO_CITLALI_IN_5_8]: {
    id: VideoSourceIds.GUIDE_TO_CITLALI_IN_5_8,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Ситлали в 5.8",
    date: "2025-08-03",
    vkvideo: "https://vkvideo.ru/video-227044935_456239245",
    youtube: "https://youtu.be/GzR7Yx8UDSM",
  },
  [VideoSourceIds.GUIDE_TO_COLUMBINA_HYPOSELENIA_IN_6_3_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_COLUMBINA_HYPOSELENIA_IN_6_3_AnimeCool,
    author: "Анимекул",
    title: "Коломбина - ИМБА Нод-Края? | Подробный гайд на Коломбину",
    date: "2026-01-14",
    vkvideo: "https://vkvideo.ru/video-231668223_456239111",
    youtube: "https://youtu.be/7_3-yO9GoOc",
  },
  [VideoSourceIds.GUIDE_TO_COLUMBINA_HYPOSELENIA_IN_6_3_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_COLUMBINA_HYPOSELENIA_IN_6_3_MironMinMax,
    author: "Miron MinMax",
    title: "Коломбина - То, Чего Все Ждали? | Гайд на Коломбину в 6.3 [Genshin Impact]",
    date: "2026-01-14",
    vkvideo: "https://vkvideo.ru/video-227044935_456239288",
    youtube: "https://youtu.be/OviJLfwfER4",
  },
  [VideoSourceIds.GUIDE_TO_DURIN_IN_6_2_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_DURIN_IN_6_2_AnimeCool,
    author: "Анимекул",
    title: "Дурин - Новая Пиро ИМБА? | Подробный гайд на Дурина",
    date: "2025-12-02",
    vkvideo: "https://vkvideo.ru/video-231668223_456239092",
    youtube: "https://youtu.be/N7NqGgOR2mA",
  },
  [VideoSourceIds.GUIDE_TO_DURIN_IN_6_2_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_DURIN_IN_6_2_MironMinMax,
    author: "Miron MinMax",
    title: "Ты Пожалеешь, что Скипнул Его | Гайд на Дурина",
    date: "2025-12-03",
    vkvideo: "https://vkvideo.ru/video-227044935_456239277",
    youtube: "https://youtu.be/s7cCUf-tQ_E",
  },
  [VideoSourceIds.GUIDE_TO_FISCHL_IN_6_2]: {
    id: VideoSourceIds.GUIDE_TO_FISCHL_IN_6_2,
    author: "Miron MinMax",
    title: "Все Ещё Имба | Подробный и Актуальный Гайд на Фишль [Genshin Impact]",
    date: "2025-12-29",
    vkvideo: "https://vkvideo.ru/video-227044935_456239285",
    youtube: "https://youtu.be/Pwe3zimTI0o",
  },
  [VideoSourceIds.GUIDE_TO_FURINA_IN_5_4]: {
    id: VideoSourceIds.GUIDE_TO_FURINA_IN_5_4,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Фурину в 5.4",
    date: "2025-03-02",
    vkvideo: "https://vkvideo.ru/video-227044935_456239203",
    youtube: "https://youtu.be/rxTakZUxk0U",
  },
  [VideoSourceIds.GUIDE_TO_ILLUGA_IN_6_3]: {
    id: VideoSourceIds.GUIDE_TO_ILLUGA_IN_6_3,
    author: "Анимекул",
    title: "Зачем нужен Иллуги? Тесты урона с Цзы Бай | Гайд на Иллуги",
    date: "2026-02-13",
    youtube: "https://youtu.be/iDOk41xI2B4",
  },
  [VideoSourceIds.GUIDE_TO_INEFFA_IN_5_8]: {
    id: VideoSourceIds.GUIDE_TO_INEFFA_IN_5_8,
    author: "Miron MinMax",
    title: "Начало Нод-Края | Гайд на Инеффу | Genshin Impact 5.8",
    date: "2025-07-30",
    vkvideo: "https://vkvideo.ru/video-227044935_456239244",
    youtube: "https://youtu.be/b5lSX3PQOuw",
  },
  [VideoSourceIds.GUIDE_TO_INEFFA_IN_6_3]: {
    id: VideoSourceIds.GUIDE_TO_INEFFA_IN_6_3,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Инеффу в 6.3",
    date: "2026-01-23",
    vkvideo: "https://vkvideo.ru/video-227044935_456239290",
    youtube: "https://youtu.be/ZqOnh55kZJc",
  },
  [VideoSourceIds.GUIDE_TO_JAHODA_IN_6_2]: {
    id: VideoSourceIds.GUIDE_TO_JAHODA_IN_6_2,
    author: "Анимекул",
    title: "Зачем нужна Ягода? | Подробный гайд на Ягоду",
    date: "2025-12-03",
    vkvideo: "https://vkvideo.ru/video-231668223_456239093",
    youtube: "https://youtu.be/LExQacPYKZc",
  },
  [VideoSourceIds.GUIDE_TO_LAUMA_IN_6_0_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_LAUMA_IN_6_0_AnimeCool,
    author: "Анимекул",
    title: "Зачем нужна Лаума? | Подробный гайд на Лауму [Genshin Impact 6.0]",
    date: "2025-09-09",
    vkvideo: "https://vkvideo.ru/video-231668223_456239063",
    youtube: "https://youtu.be/Y2XmxQHkY6g",
  },
  [VideoSourceIds.GUIDE_TO_LAUMA_IN_6_0_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_LAUMA_IN_6_0_MironMinMax,
    author: "Miron MinMax",
    title: "Паверкрип Нахиды? Гайд на Лауму в 6.0",
    date: "2025-09-10",
    vkvideo: "https://vkvideo.ru/video-227044935_456239254",
    youtube: "https://youtu.be/BMpFDebyZck",
  },
  [VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_AnimeCool,
    author: "Анимекул",
    title: "Кирилл Флинс - ИМБА? | Подробный гайд на Флинса [Genshin Impact]",
    date: "2025-09-30",
    vkvideo: "https://vkvideo.ru/video-231668223_456239067",
    youtube: "https://youtu.be/WstroDNl-Ps",
  },
  [VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_MironMinMax,
    author: "Miron MinMax",
    title: "Кирилл - Имба, Слабый или просто ОК? Гайд на Флинса",
    date: "2025-09-30",
    vkvideo: "https://vkvideo.ru/video-227044935_456239259",
    youtube: "https://youtu.be/ip1jJz-a4Fc",
  },
  [VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_xPandaChannelx]: {
    id: VideoSourceIds.GUIDE_TO_KYRYLL_CHUDOMIROVICH_FLINS_IN_6_0_xPandaChannelx,
    author: "xPandaChannelx",
    title: "Кирилл Чудомирович Флинс | Крутки/Гайд | Flins Гайд Геншин Импакт Луна I",
    date: "2025-09-30",
    vkvideo: "https://vkvideo.ru/video-226836627_456239504",
  },
  [VideoSourceIds.GUIDE_TO_MAVUIKA]: {
    id: VideoSourceIds.GUIDE_TO_MAVUIKA,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Мавуику",
    date: "2025-07-08",
    vkvideo: "https://vkvideo.ru/video-227044935_456239238",
    youtube: "https://youtu.be/bGkCi_aBNrI",
  },
  [VideoSourceIds.GUIDE_TO_MUALANI_IN_5_8]: {
    id: VideoSourceIds.GUIDE_TO_MUALANI_IN_5_8,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Муалани в 5.8",
    date: "2025-08-18",
    vkvideo: "https://vkvideo.ru/video-227044935_456239248",
    youtube: "https://youtu.be/xEglYZO38Rs",
  },
  [VideoSourceIds.GUIDE_TO_NAHIDA_IN_5_1]: {
    id: VideoSourceIds.GUIDE_TO_NAHIDA_IN_5_1,
    author: "Miron MinMax",
    title: "Актуальный и Подробный | Гайд на Нахиду в 5.1",
    date: "2024-10-23",
    vkvideo: "https://vk.com/video-227044935_456239163",
    youtube: "https://youtu.be/QZObIiFe8R8",
  },
  [VideoSourceIds.GUIDE_TO_NEFER_IN_6_1_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_NEFER_IN_6_1_AnimeCool,
    author: "Анимекул",
    title: "Нефер - Новая Дендро ИМБА? | Полный гайд на Нефер [Genshin Impact 6.1]",
    date: "2025-10-23",
    vkvideo: "https://vkvideo.ru/video-231668223_456239074",
    youtube: "https://youtu.be/o5ulYPCoEF4",
  },
  [VideoSourceIds.GUIDE_TO_NEFER_IN_6_1_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_NEFER_IN_6_1_MironMinMax,
    author: "Miron MinMax",
    title: "Нефер - Новая Дендро Имба? Гайд на Нефер в 6.1 [Genshin Impact]",
    date: "2025-10-22",
    vkvideo: "https://vkvideo.ru/video-227044935_456239266",
    youtube: "https://youtu.be/DcbkdNYCaqM",
  },
  [VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_5_2]: {
    id: VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_5_2,
    author: "Miron MinMax",
    title: "Актуальный и Подробный | Гайд на Нёвилетта в 5.2",
    date: "2024-12-11",
    vkvideo: "https://vkvideo.ru/video-227044935_456239180",
    youtube: "https://youtu.be/IoGwHEPCnYs",
  },
  [VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_6_3_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_6_3_AnimeCool,
    author: "Анимекул",
    title: "Актуален ли Нёвиллет? Урон Нёвиллета | Обновлённый гайд (6.3)",
    date: "2026-02-07",
    vkvideo: "https://vkvideo.ru/video-231668223_456239118",
    youtube: "https://youtu.be/FS8kKRglFbI",
  },
  [VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_6_3_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_NEUVILLETTE_IN_6_3_MironMinMax,
    author: "Miron MinMax",
    title: "Нёвиллет ещё Актуален? Дополнение к Гайду [Genshin Impact 6.3]",
    date: "2026-02-10",
    vkvideo: "https://vkvideo.ru/video-227044935_456239296",
    youtube: "https://youtu.be/YUsnkh4oGKU",
  },
  [VideoSourceIds.GUIDE_TO_RAIDEN_SHOGUN_IN_5_0]: {
    id: VideoSourceIds.GUIDE_TO_RAIDEN_SHOGUN_IN_5_0,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Райдэн в 5.0",
    date: "2024-10-02",
    vkvideo: "https://vk.com/video-227044935_456239156",
    youtube: "https://youtu.be/sDmNHMtfrhc",
  },
  [VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_AnimeCool,
    author: "Анимекул",
    title: "Скирк – заложник Эскофье или имба? | Подробный гайд на Скирк",
    date: "2025-06-17",
    vkvideo: "https://vkvideo.ru/video-231668223_456239022",
    youtube: "https://youtu.be/5ZoCR8bsSYM",
  },
  [VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_MironMinMax,
    author: "Miron MinMax",
    title: "Скирк - Сильнейший Крио (но есть нюанс)",
    date: "2025-06-18",
    vkvideo: "https://vkvideo.ru/video-227044935_456239232",
    youtube: "https://youtu.be/jpAMI38M-LI",
  },
  [VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_xPandaChannelx]: {
    id: VideoSourceIds.GUIDE_TO_SKIRK_IN_5_7_xPandaChannelx,
    author: "xPandaChannelx",
    title: "Скирк Гайд | Ротации/Шмотки/Группы/F2P | Skirk Как Играть Геншин Импакт 5.7",
    date: "2025-06-19",
    vkvideo: "https://vkvideo.ru/video-226836627_456239384",
    youtube: "https://www.youtube.com/watch?v=Rr26SHvbmXE",
  },
  [VideoSourceIds.GUIDE_TO_TRAVELER_PYRO]: {
    id: VideoSourceIds.GUIDE_TO_TRAVELER_PYRO,
    author: "Анимекул",
    title: "Зачем нужен Пиро Путешественник? | Подробный гайд на Пиро ГГ",
    date: "2025-01-08",
    vkvideo: "https://vkvideo.ru/video-229156089_456239059",
    youtube: "https://youtu.be/L3Eg506_w7M",
  },
  [VideoSourceIds.GUIDE_TO_VARESA_IN_6_2_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_VARESA_IN_6_2_AnimeCool,
    author: "Анимекул",
    title: "Актуальна ли Вареса? | Обновлённый гайд на Варесу",
    date: "2025-12-21",
    vkvideo: "https://vkvideo.ru/video-231668223_456239107",
    youtube: "https://youtu.be/j2UJtlB2f3I",
  },
  [VideoSourceIds.GUIDE_TO_VARESA_IN_6_2_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_VARESA_IN_6_2_MironMinMax,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Варесу в 6.2 [Genshin Impact]",
    date: "2025-12-23",
    vkvideo: "https://vkvideo.ru/video-227044935_456239283",
    youtube: "https://youtu.be/mZE4e2S_S0g",
  },
  [VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_AnimeCool,
    author: "Анимекул",
    title: "Варка - Очередной Анемо ДД? | Подробный гайд на Варку",
    date: "2026-02-24",
    // vkvideo: "",
    youtube: "https://youtu.be/T2e3ep_pfEI",
  },
  [VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_MironMinMax,
    author: "Miron MinMax",
    title: "Неужели Все Настолько Плохо | Гайд на Варку",
    date: "2026-02-25",
    // vkvideo: "",
    youtube: "https://youtu.be/tnxVEGNyJJ4",
  },
  [VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_xPandaChannelx]: {
    id: VideoSourceIds.GUIDE_TO_VARKA_IN_6_4_xPandaChannelx,
    author: "xPandaChannelx",
    title: "Варка - Бесполезный Персонаж? | Объедки IWinToLose Gaming | Varka Гайд Геншин Импакт 6.4",
    date: "2026-02-19",
    vkvideo: "https://vkvideo.ru/video-226836627_456239658",
    youtube: "https://www.youtube.com/watch?v=NFkA8f5FA-8",
  },
  [VideoSourceIds.GUIDE_TO_VENTI_IN_6_2]: {
    id: VideoSourceIds.GUIDE_TO_VENTI_IN_6_2,
    author: "Анимекул",
    title: "Новый Венти ИМБА? | Подробный гайд на Венти 6.2",
    date: "2025-12-05",
    vkvideo: "https://vkvideo.ru/video-231668223_456239096",
    youtube: "https://youtu.be/X81tzU7NNws",
  },
  [VideoSourceIds.GUIDE_TO_XIANGLING_IN_6_0]: {
    id: VideoSourceIds.GUIDE_TO_XIANGLING_IN_6_0,
    author: "Miron MinMax",
    title: "Подробный и Актуальный | Гайд на Сян Лин в 6.0",
    date: "2025-10-06",
    vkvideo: "https://vkvideo.ru/video-227044935_456239260",
    youtube: "https://youtu.be/FhKKE0H9K8o",
  },
  [VideoSourceIds.GUIDE_TO_ZIBAI_IN_6_3_AnimeCool]: {
    id: VideoSourceIds.GUIDE_TO_ZIBAI_IN_6_3_AnimeCool,
    author: "Анимекул",
    title: "Цзы Бай - Новая Гео ИМБА? | Подробный гайд на Цзы Бай",
    date: "2026-02-01",
    vkvideo: "https://vkvideo.ru/video-231668223_456239117",
    youtube: "https://youtu.be/6fe2FBppLRc",
  },
  [VideoSourceIds.GUIDE_TO_ZIBAI_IN_6_3_MironMinMax]: {
    id: VideoSourceIds.GUIDE_TO_ZIBAI_IN_6_3_MironMinMax,
    author: "Miron MinMax",
    title: "Цзы Бай - Очередная Имба Нод Края? Гайд на Цзы Бай в 6.3 [Genshin Impact]",
    date: "2026-02-03",
    vkvideo: "https://vkvideo.ru/video-227044935_456239295",
    youtube: "https://youtu.be/9jAJnci_-HM",
  },
  [VideoSourceIds.HOW_GOOD_IS_RAIDEN_SHOGUN_CONSTELLATIONS]: {
    id: VideoSourceIds.HOW_GOOD_IS_RAIDEN_SHOGUN_CONSTELLATIONS,
    author: "Miron MinMax",
    title: "Насколько Хороши Созвездия Райдэн | И хороши ли?",
    date: "2025-05-30",
    vkvideo: "https://vkvideo.ru/video-227044935_456239227",
    youtube: "https://youtu.be/dzI9MhNl5Ic",
  },
  [VideoSourceIds.TALENT_GAINS_ANEMO]: {
    id: VideoSourceIds.TALENT_GAINS_ANEMO,
    author: "Miron MinMax",
    title: "Приросты от Талантов | Анемо [Genshin Impact]",
    date: "2025-11-24",
    vkvideo: "https://vkvideo.ru/video-227044935_456239274",
    youtube: "https://youtu.be/aKZUsonvv4E",
  },
  [VideoSourceIds.TALENT_GAINS_GEO]: {
    id: VideoSourceIds.TALENT_GAINS_GEO,
    author: "Miron MinMax",
    title: "Приросты от Талантов | Гео [Genshin Impact]",
    date: "2026-01-31",
    vkvideo: "https://vkvideo.ru/video-227044935_456239294",
    youtube: "https://youtu.be/B5cKoaBaYrg",
  },
  [VideoSourceIds.TALENT_GAINS_HYDRO]: {
    id: VideoSourceIds.TALENT_GAINS_HYDRO,
    author: "Miron MinMax",
    title: "Приросты от Талантов | Гидро [Genshin Impact]",
    date: "2025-12-14",
    vkvideo: "https://vkvideo.ru/video-227044935_456239280",
    youtube: "https://youtu.be/iT7NTPfNlwk",
  },
  [VideoSourceIds.TALENT_GAINS_PYRO]: {
    id: VideoSourceIds.TALENT_GAINS_PYRO,
    author: "Miron MinMax",
    title: "Приросты от Талантов | Пиро [Genshin Impact]",
    date: "2026-02-22",
    vkvideo: "https://vkvideo.ru/video-227044935_456239299",
    youtube: "https://youtu.be/FtKtaJNTYkw",
  },
  [VideoSourceIds.THE_BEST_AVAILABLE_WEAPONS_FOR_EVERY_CHARACTER]: {
    id: VideoSourceIds.THE_BEST_AVAILABLE_WEAPONS_FOR_EVERY_CHARACTER,
    author: "Miron MinMax",
    title: "Лучшее Доступное Оружие для Каждого Персонажа",
    date: "2024-11-10",
    vkvideo: "https://vk.com/video-227044935_456239169",
    youtube: "https://youtu.be/zVspDJZPa4Y",
  },
  [VideoSourceIds.THE_BEST_WEAPONS_FOR_EVERY_CHARACTER]: {
    id: VideoSourceIds.THE_BEST_WEAPONS_FOR_EVERY_CHARACTER,
    author: "Miron MinMax",
    title: "Лучшее Оружие для Каждого Персонажа",
    date: "2024-11-03",
    vkvideo: "https://vk.com/video-227044935_456239166",
    youtube: "https://youtu.be/cjatyGw0EO0",
  },
  [VideoSourceIds.WHO_NEEDS_LEVELING_PART_1]: {
    id: VideoSourceIds.WHO_NEEDS_LEVELING_PART_1,
    author: "Miron MinMax",
    title: "КОМУ КАЧАТЬ УРОВЕНЬ? ВСЕ ПЕРСОНАЖИ Ч.1 feat.@AnimeCool_Genshin",
    date: "2023-09-23",
    vkvideo: "https://vkvideo.ru/video-227044935_456239108",
    youtube: "https://youtu.be/lhEME9s3HO0",
  },
  [VideoSourceIds.WHO_NEEDS_LEVELING_PART_2]: {
    id: VideoSourceIds.WHO_NEEDS_LEVELING_PART_2,
    author: "Miron MinMax",
    title: "КОМУ КАЧАТЬ УРОВЕНЬ? ВСЕ ПЕРСОНАЖИ Ч.2 feat.@AnimeCool_Genshin",
    date: "2023-09-25",
    vkvideo: "https://vkvideo.ru/video-227044935_456239106",
    youtube: "https://youtu.be/Yz95Iw1q-es",
  },
  [VideoSourceIds.XIANGLING_ELEMENTAL_BURST_GUIDE]: {
    id: VideoSourceIds.XIANGLING_ELEMENTAL_BURST_GUIDE,
    author: "spartanchick",
    title: "Как УМНОЖИТЬ свой УРОН? Гайд на ульту Сян Лин от киберспортсмена",
    date: "2024-08-25",
    youtube: "https://youtu.be/ys7fhxFf6Tc",
  },
});

export type VideoSourcesState = typeof initialState;

export const videoSourcesSlice = createSlice<VideoSourcesState, SliceCaseReducers<VideoSourcesState>, string, SliceSelectors<VideoSourcesState>, string>({
  name: "videoSources",
  initialState,
  reducers: {},
});

export default videoSourcesSlice.reducer;

export const { selectAll: selectAllVideoSources } = videoSourcesAdapter.getSelectors((state: {
  videoSources: VideoSourcesState;
}) => state.videoSources);

export const selectVideoSourcesByIds = createSelector(
  [selectAllVideoSources, (_, ids: VideoSourceId[]) => ids],
  (videoSources, ids) => videoSources.filter(videoSource => ids.includes(videoSource.id)),
);
