import type { Weapon as WeaponDB } from "genshin-db";

export const WeaponNames = {
  A_THOUSAND_BLAZING_SUNS: "Тысяча ослепительных солнц",
  A_THOUSAND_FLOATING_DREAMS: "Сновидения тысячи ночей",
  ABSOLUTION: "Отпущение грехов",
  AKUOUMARU: "Акуомару",
  ALLEY_HUNTER: "Охотник во тьме",
  AMENOMA_KAGEUCHI: "Амэнома Кагэути",
  AMOS_BOW: "Лук Амоса",
  AQUA_SIMULACRA: "Аква симулякрум",
  AQUILA_FAVONIA: "Меч Сокола",
  ASH_GRAVEN_DRINKING_HORN: "Пепельный рог",
  ASTRAL_VULTURES_CRIMSON_PLUMAGE: "Алое перо звёздного грифа",
  ATHAME_ARTIS: "Атаме артис",
  AZURELIGHT: "Лазурное сияние",
  BALLAD_OF_THE_FJORDS: "Баллада фьордов",
  BEACON_OF_THE_REED_SEA: "Маяк тростникового моря",
  BLACK_TASSEL: "Чёрная кисть",
  BLACKCLIFF_LONGSWORD: "Черногорский длинный меч",
  BLACKCLIFF_POLE: "Черногорская пика",
  BLACKCLIFF_SLASHER: "Черногорская бритва",
  BLACKCLIFF_WARBOW: "Черногорский боевой лук",
  BLACKMARROW_LANTERN: "Фонарь чёрной сердцевины",
  BLOODSOAKED_RUINS: "Окровавленные руины",
  BLOODTAINTED_GREATSWORD: "Меч драконьей крови",
  CALAMITY_OF_ESHU: "Бедствие Эшу",
  CALAMITY_QUELLER: "Усмиритель бед",
  CASHFLOW_SUPERVISION: "Казначейский надзор",
  CHAIN_BREAKER: "Разбивающий цепи",
  CINNABAR_SPINDLE: "Киноварное веретено",
  CRANES_ECHOING_CALL: "Звонкий клич журавля",
  CRIMSON_MOONS_SEMBLANCE: "Очертания алой луны",
  DAWNING_FROST: "Рассветный иней",
  DEATHMATCH: "Смертельный бой",
  DIALOGUES_OF_THE_DESERT_SAGES: "Диалог пустынных мудрецов",
  DODOCO_TALES: "Истории Додоко",
  DRAGONS_BANE: "Гроза драконов",
  EARTH_SHAKER: "Сотрясающий землю",
  ELEGY_FOR_THE_END: "Элегия погибели",
  ENGULFING_LIGHTNING: "Сияющая жатва",
  ETHERLIGHT_SPINDLELUTE: "Лютня ткача света",
  EVERLASTING_MOONGLOW: "Вечное лунное сияние",
  FADING_TWILIGHT: "Гаснущие сумерки",
  FANG_OF_THE_MOUNTAIN_KING: "Клык Горного короля",
  FAVONIUS_CODEX: "Кодекс Фавония",
  FAVONIUS_GREATSWORD: "Двуручный меч Фавония",
  FAVONIUS_LANCE: "Копьё Фавония",
  FAVONIUS_SWORD: "Меч Фавония",
  FAVONIUS_WARBOW: "Боевой лук Фавония",
  FESTERING_DESIRE: "Осквернённое желание",
  FINALE_OF_THE_DEEP: "Грандиозный финал глубин",
  FLAME_FORGED_INSIGHT: "Выкованное пламенем озарение",
  FLEUVE_CENDRE_FERRYMAN: "Перевозчик Флёв Сандр",
  FLOWING_PURITY: "Сверкание чистых вод",
  FLUTE_OF_EZPITZAL: "Флейта Эспицаль",
  FOOTPRINT_OF_THE_RAINBOW: "След радуги",
  FRACTURED_HALO: "Расколотый ореол",
  FREEDOM_SWORN: "Клятва свободы",
  HAKUSHIN_RING: "Кольцо Хакусин",
  HAMAYUMI: "Хамаюми",
  HARAN_GEPPAKU_FUTSU: "Харан гэппаку фуцу",
  HARBINGER_OF_DAWN: "Предвестник зари",
  HUNTERS_PATH: "Охотничья тропа",
  IRON_STING: "Стальное жало",
  JADEFALLS_SPLENDOR: "Великолепие лазурного свода",
  KAGURAS_VERITY: "Истина кагура",
  KEY_OF_KHAJ_NISUT: "Ключ Хадж-нисут",
  KITAIN_CROSS_SPEAR: "Крест-копьё Китаин",
  LIGHT_OF_FOLIAR_INCISION: "Свет лиственного разреза",
  LIONS_ROAR: "Драконий рык",
  LITHIC_SPEAR: "Каменное копьё",
  LOST_PRAYER_TO_THE_SACRED_WINDS: "Молитва святым ветрам",
  LUMIDOUCE_ELEGY: "Элегия Люмидус",
  LUXURIOUS_SEA_LORD: "Благодатный владыка вод",
  MAGIC_GUIDE: "Руководство по магии",
  MAILED_FLOWER: "Цветок в латах",
  MAKHAIRA_AQUAMARINE: "Аквамарин Махайры",
  MAPPA_MARE: "Морской атлас",
  MASTER_KEY: "Мастер-ключ",
  MEMORY_OF_DUST: "Память о пыли",
  MISSIVE_WINDSPEAR: "Копьё послания ветров",
  MISTSPLITTER_REFORGED: "Рассекающий туман",
  MOONWEAVERS_DAWN: "Рассвет прядильщицы луны",
  NIGHTWEAVERS_LOOKING_GLASS: "Зеркало прядильщицы ночи",
  OATHSWORN_EYE: "Око клятвы",
  PEAK_PATROL_SONG: "Песнь патруля пиков",
  POLAR_STAR: "Полярная звезда",
  PREDATOR: "Хищник",
  PRIMORDIAL_JADE_CUTTER: "Драгоценный омут",
  PRIMORDIAL_JADE_WINGED_SPEAR: "Нефритовый коршун",
  PROSPECTORS_DRILL: "Бур рудоискателя",
  PROSPECTORS_SHOVEL: "Лопата старателя",
  PROTOTYPE_AMBER: "Прототип: Янтарь",
  PROTOTYPE_ARCHAIC: "Прототип: Архаичный",
  PROTOTYPE_CRESCENT: "Прототип: Полумесяц",
  RAINBOW_SERPENTS_RAIN_BOW: "Струны дождя радужного змея",
  RAINSLASHER: "Дождерез",
  RANGE_GAUGE: "Дальномер",
  RECURVE_BOW: "Изогнутый лук",
  REDHORN_STONETHRESHER: "Краснорогий камнеруб",
  RELIQUARY_OF_TRUTH: "Шкатулка истин",
  RIGHTFUL_REWARD: "Справедливая награда",
  RING_OF_YAXCHE: "Кольцо Яшче",
  RUST: "Ржавый лук",
  SACRIFICIAL_BOW: "Церемониальный лук",
  SACRIFICIAL_FRAGMENTS: "Церемониальные мемуары",
  SACRIFICIAL_GREATSWORD: "Церемониальный двуручный меч",
  SACRIFICIAL_JADE: "Жертвенный нефрит",
  SACRIFICIAL_SWORD: "Церемониальный меч",
  SAPWOOD_BLADE: "Деревянный клинок",
  SCION_OF_THE_BLAZING_SUN: "Наследник слепящего солнца",
  SERPENT_SPINE: "Меч драконьей кости",
  SILVERSHOWER_HEARTSTRINGS: "Сердечные струны дождя",
  SKYWARD_ATLAS: "Небесный атлас",
  SKYWARD_BLADE: "Небесный меч",
  SKYWARD_HARP: "Небесное крыло",
  SKYWARD_PRIDE: "Небесное величие",
  SKYWARD_SPINE: "Небесная ось",
  SLINGSHOT: "Рогатка",
  SNARE_HOOK: "Крюк силка",
  SOLAR_PEARL: "Солнечная жемчужина",
  SONG_OF_BROKEN_PINES: "Песнь разбитых сосен",
  SONG_OF_STILLNESS: "Мелодия покоя",
  SPLENDOR_OF_TRANQUIL_WATERS: "Блеск тихих вод",
  STAFF_OF_HOMA: "Посох Хомы",
  STAFF_OF_THE_SCARLET_SANDS: "Посох алых песков",
  STARCALLERS_WATCH: "Бдение взывающего к звёздам",
  SUMMIT_SHAPER: "Кромсатель пиков",
  SUNNY_MORNING_SLEEP_IN: "Сон солнечным утром",
  SURFS_UP: "Лови волну",
  SYMPHONIST_OF_SCENTS: "Симфонист ароматов",
  TALKING_STICK: "Говорящая палица",
  TAMAYURATEI_NO_OHANASHI: "Тамаюратэй но оханаси",
  THE_BLACK_SWORD: "Чёрный меч",
  THE_CATCH: "«Улов»",
  THE_DAYBREAK_CHRONICLES: "Хроники рассвета",
  THE_DOCKHANDS_ASSISTANT: "Верфь",
  THE_FIRST_GREAT_MAGIC: "Первый великий фокус",
  THE_STRINGLESS: "Бесструнный",
  THE_UNFORGED: "Некованый",
  THE_VIRIDESCENT_HUNT: "Зелёный лук",
  THE_WIDSITH: "Песнь странника",
  THRILLING_TALES_OF_DRAGON_SLAYERS: "Эпос о драконоборцах",
  THUNDERING_PULSE: "Громовой пульс",
  TIDAL_SHADOW: "Тень волны",
  TOME_OF_THE_ETERNAL_FLOW: "Обряд вечного течения",
  TOUKABOU_SHIGURE: "Токабо сигурэ",
  TULAYTULLAHS_REMEMBRANCE: "Воспоминания Тулайтуллы",
  ULTIMATE_OVERLORDS_MEGA_MAGIC_SWORD: "«Магический супермеч высшего владыки»",
  URAKU_MISUGIRI: "Ураку мисугири",
  VERDICT: "Вердикт",
  VIViD_NOTIONS: "Переливающиеся чаяния",
  VORTEX_VANQUISHER: "Покоритель вихря",
  WANDERING_EVENSTAR: "Скитающаяся звезда",
  WAVEBREAKERS_FIN: "Режущий волны плавник",
  WHITE_TASSEL: "Белая кисть",
  WHITEBLIND: "Белая тень",
  WINDBLUME_ODE: "Ода анемонии",
  WOLF_FANG: "Волчий клык",
  WOLFS_GRAVESTONE: "Волчья погибель",
  XIPHOS_MOONLIGHT: "Лунное сияние ксифоса",
} as const;

export type WeaponName = typeof WeaponNames[keyof typeof WeaponNames];

export interface Weapon extends Omit<WeaponDB, "stats"> {
  name: WeaponName;
}
