export const CharacterRoleIds = {
  ON_FIELD: "on-field",
  OFF_FIELD: "off-field",
  DPS: "dps",
  SUPPORT: "support",
  SURVIVABILITY: "survivability",
} as const;
export const ElementNames = {
  ANEMO: "Анемо",
  CRYO: "Крио",
  DENDRO: "Дендро",
  ELECTRO: "Электро",
  GEO: "Гео",
  HYDRO: "Гидро",
  PYRO: "Пиро",
} as const;
export const VideoSourceIds = {
  ALL_ABOUT_ALL_TALENTS: "all_about_all_talents",
  FIRST_CONSTELLATION_OR_SIGNATURE_WEAPON: "first_constellation_or_signature_weapon",
  GUIDE_TO_AINO_IN_6_0: "guide_to_Aino_in_6.0",
  GUIDE_TO_ARLECCHINO_IN_5_3: "guide_to_Arlecchino_in_5.3",
  GUIDE_TO_DURIN_IN_6_2_AnimeCool: "guide_to_Durin_in_6.2_AnimeCool",
  GUIDE_TO_DURIN_IN_6_2_MironMinMax: "guide_to_Durin_in_6.2_MironMinMax",
  GUIDE_TO_FISCHL_IN_6_2: "guide_to_Fischl_in_6.2",
  GUIDE_TO_INEFFA_IN_5_8: "guide_to_Ineffa_in_5.8",
  GUIDE_TO_JAHODA_IN_6_2: "guide_to_Jahoda_in_6.2",
  GUIDE_TO_VARESA_IN_6_2_AnimeCool: "guide_to_Varesa_in_6.2_AnimeCool",
  GUIDE_TO_VARESA_IN_6_2_MironMinMax: "guide_to_Varesa_in_6.2_MironMinMax",
  GUIDE_TO_VENTI_IN_6_2: "guide_to_Venti_in_6.2",
  THE_BEST_AVAILABLE_WEAPONS_FOR_EVERY_CHARACTER: "the_best_available_weapons_for_every_character",
  THE_BEST_WEAPONS_FOR_EVERY_CHARACTER: "the_best_weapons_for_every_character",
  WHO_NEEDS_LEVELING_PART_1: "who_needs_leveling_part_1",
  WHO_NEEDS_LEVELING_PART_2: "who_needs_leveling_part_2",
} as const;
export const WeaponNames = {
  A_THOUSAND_FLOATING_DREAMS: "Сновидения тысячи ночей",
  ABSOLUTION: "Отпущение грехов",
  ALLEY_HUNTER: "Охотник во тьме",
  AMENOMA_KAGEUCHI: "Амэнома Кагэути",
  AMOS_BOW: "Лук Амоса",
  AQUA_SIMULACRA: "Аква симулякрум",
  AQUILA_FAVONIA: "Меч Сокола",
  ASTRAL_VULTURES_CRIMSON_PLUMAGE: "Алое перо звёздного грифа",
  ATHAME_ARTIS: "Атаме артис",
  AZURELIGHT: "Лазурное сияние",
  BALLAD_OF_THE_FJORDS: "Баллада фьордов",
  BEACON_OF_THE_REED_SEA: "Маяк тростникового моря",
  BLACKCLIFF_LONGSWORD: "Черногорский длинный меч",
  BLACKCLIFF_POLE: "Черногорская пика",
  BLACKCLIFF_SLASHER: "Черногорская бритва",
  BLACKCLIFF_WARBOW: "Черногорский боевой лук",
  CALAMITY_QUELLER: "Усмиритель бед",
  CASHFLOW_SUPERVISION: "Казначейский надзор",
  CHAIN_BREAKER: "Разбивающий цепи",
  CINNABAR_SPINDLE: "Киноварное веретено",
  CRANES_ECHOING_CALL: "Звонкий клич журавля",
  CRIMSON_MOONS_SEMBLANCE: "Очертания алой луны",
  DEATHMATCH: "Смертельный бой",
  DRAGONS_BANE: "Гроза драконов",
  EARTH_SHAKER: "Сотрясающий землю",
  ELEGY_FOR_THE_END: "Элегия погибели",
  ENGULFING_LIGHTNING: "Сияющая жатва",
  FADING_TWILIGHT: "Гаснущие сумерки",
  FANG_OF_THE_MOUNTAIN_KING: "Клык Горного короля",
  FAVONIUS_CODEX: "Кодекс Фавония",
  FAVONIUS_GREATSWORD: "Двуручный меч Фавония",
  FAVONIUS_LANCE: "Копьё Фавония",
  FAVONIUS_SWORD: "Меч Фавония",
  FAVONIUS_WARBOW: "Боевой лук Фавония",
  FESTERING_DESIRE: "Осквернённое желание",
  FINALE_OF_THE_DEEP: "Грандиозный финал глубин",
  FLAME_FORGED_INSIGHT: "Выкованное пламенем озарение",
  FLOWING_PURITY: "Сверкание чистых вод",
  FLUTE_OF_EZPITZAL: "Флейта Эспицаль",
  FRACTURED_HALO: "Расколотый ореол",
  FREEDOM_SWORN: "Клятва свободы",
  HAKUSHIN_RING: "Кольцо Хакусин",
  HAMAYUMI: "Хамаюми",
  HARAN_GEPPAKU_FUTSU: "Харан гэппаку фуцу",
  HARBINGER_OF_DAWN: "Предвестник зари",
  HUNTERS_PATH: "Охотничья тропа",
  IRON_STING: "Стальное жало",
  JADEFALLS_SPLENDOR: "Великолепие лазурного свода",
  KAGURAS_VERITY: "Истина кагура",
  KITAIN_CROSS_SPEAR: "Крест-копьё Китаин",
  LIGHT_OF_FOLIAR_INCISION: "Свет лиственного разреза",
  LIONS_ROAR: "Драконий рык",
  LITHIC_SPEAR: "Каменное копьё",
  LOST_PRAYER_TO_THE_SACRED_WINDS: "Молитва святым ветрам",
  LUMIDOUCE_ELEGY: "Элегия Люмидус",
  MAKHAIRA_AQUAMARINE: "Аквамарин Махайры",
  MASTER_KEY: "Мастер-ключ",
  MEMORY_OF_DUST: "Память о пыли",
  MISSIVE_WINDSPEAR: "Копьё послания ветров",
  MISTSPLITTER_REFORGED: "Рассекающий туман",
  MOONWEAVERS_DAWN: "Рассвет прядильщицы луны",
  POLAR_STAR: "Полярная звезда",
  PRIMORDIAL_JADE_CUTTER: "Драгоценный омут",
  PRIMORDIAL_JADE_WINGED_SPEAR: "Нефритовый коршун",
  PROTOTYPE_AMBER: "Прототип: Янтарь",
  RAINBOW_SERPENTS_RAIN_BOW: "Струны дождя радужного змея",
  RAINSLASHER: "Дождерез",
  RANGE_GAUGE: "Дальномер",
  REDHORN_STONETHRESHER: "Краснорогий камнеруб",
  RUST: "Ржавый лук",
  SACRIFICIAL_BOW: "Церемониальный лук",
  SACRIFICIAL_FRAGMENTS: "Церемониальные мемуары",
  SACRIFICIAL_GREATSWORD: "Церемониальный двуручный меч",
  SACRIFICIAL_JADE: "Жертвенный нефрит",
  SAPWOOD_BLADE: "Деревянный клинок",
  SCION_OF_THE_BLAZING_SUN: "Наследник слепящего солнца",
  SERPENT_SPINE: "Меч драконьей кости",
  SKYWARD_ATLAS: "Небесный атлас",
  SKYWARD_BLADE: "Небесный меч",
  SKYWARD_HARP: "Небесное крыло",
  SKYWARD_PRIDE: "Небесное величие",
  SKYWARD_SPINE: "Небесная ось",
  SLINGSHOT: "Рогатка",
  SNARE_HOOK: "Крюк силка",
  SONG_OF_STILLNESS: "Мелодия покоя",
  STAFF_OF_HOMA: "Посох Хомы",
  STAFF_OF_THE_SCARLET_SANDS: "Посох алых песков",
  SURFS_UP: "Лови волну",
  SYMPHONIST_OF_SCENTS: "Симфонист ароматов",
  TAMAYURATEI_NO_OHANASHI: "Тамаюратэй но оханаси",
  THE_BLACK_SWORD: "Чёрный меч",
  THE_DAYBREAK_CHRONICLES: "Хроники рассвета",
  THE_FIRST_GREAT_MAGIC: "Первый великий фокус",
  THE_STRINGLESS: "Бесструнный",
  THE_VIRIDESCENT_HUNT: "Зелёный лук",
  THE_WIDSITH: "Песнь странника",
  THRILLING_TALES_OF_DRAGON_SLAYERS: "Эпос о драконоборцах",
  THUNDERING_PULSE: "Громовой пульс",
  TIDAL_SHADOW: "Тень волны",
  TOME_OF_THE_ETERNAL_FLOW: "Обряд вечного течения",
  TOUKABOU_SHIGURE: "Токабо сигурэ",
  TULAYTULLAHS_REMEMBRANCE: "Воспоминания Тулайтуллы",
  ULTIMATE_OVERLORDS_MEGA_MAGIC_SWORD: "«Магический супермеч высшего владыки»",
  URAKU_MISUGIRI: "Ураку мисугири",
  VIViD_NOTIONS: "Переливающиеся чаяния",
  VORTEX_VANQUISHER: "Покоритель вихря",
  WAVEBREAKERS_FIN: "Режущий волны плавник",
  WHITE_TASSEL: "Белая кисть",
  WHITEBLIND: "Белая тень",
  WINDBLUME_ODE: "Ода анемонии",
  WOLF_FANG: "Волчий клык",
  WOLFS_GRAVESTONE: "Волчья погибель",
  XIPHOS_MOONLIGHT: "Лунное сияние ксифоса",
} as const;

export type CharacterRoleId = typeof CharacterRoleIds[keyof typeof CharacterRoleIds];
export type ElementName = typeof ElementNames[keyof typeof ElementNames];
export type Rarity = 1 | 2 | 3 | 4 | 5;
export type VideoSourceId = typeof VideoSourceIds[keyof typeof VideoSourceIds];
export type WeaponName = typeof WeaponNames[keyof typeof WeaponNames];

export interface CharacterRole {
  id: CharacterRoleId;
  name: string;
  description: string;
  image: string;
}

export interface VideoSource {
  id: VideoSourceId;
  author: string;
  title: string;
  date: string;
  rutube?: string;
  vkvideo?: string;
  youtube?: string;
}
