import type { ElementId, ElementName } from "./elements.types";
import type { Rarity } from "./rarities.types";

export const CharacterIds = {
  AETHER: "aether",
  AINO: "aino",
  ALBEDO: "albedo",
  ALHAITHAM: "alhaitham",
  ALOY: "aloy",
  AMBER: "amber",
  ARATAKI_ITTO: "arataki_itto",
  ARLECCHINO: "arlecchino",
  BAIZHU: "baizhu",
  BARBARA: "barbara",
  BEIDOU: "beidou",
  BENNETT: "bennett",
  CANDACE: "candace",
  CHARLOTTE: "charlotte",
  CHASCA: "chasca",
  CHEVREUSE: "chevreuse",
  CHIORI: "chiori",
  CHONGYUN: "chongyun",
  CITLALI: "citlali",
  CLORINDE: "clorinde",
  COLLEI: "collei",
  COLUMBINA_HYPOSELENIA: "columbina",
  CYNO: "cyno",
  DAHLIA: "dahlia",
  DEHYA: "dehya",
  DILUC: "diluc",
  DIONA: "diona",
  DORI: "dori",
  DURIN: "durin",
  EMILIE: "emilie",
  ESCOFFIER: "escoffier",
  EULA: "eula",
  FARUZAN: "faruzan",
  FISCHL: "fischl",
  FREMINET: "freminet",
  FURINA: "furina",
  GAMING: "gaming",
  GANYU: "ganyu",
  GOROU: "gorou",
  HU_TAO: "hu_tao",
  IANSAN: "iansan",
  IFA: "ifa",
  ILLUGA: "illuga",
  INEFFA: "ineffa",
  JAHODA: "jahoda",
  JEAN: "jean",
  KACHINA: "kachina",
  KAEDEHARA_KAZUHA: "kaedehara_kazuha",
  KAEYA: "kaeya",
  KAMISATO_AYAKA: "kamisato_ayaka",
  KAMISATO_AYATO: "kamisato_ayato",
  KAVEH: "kaveh",
  KEQING: "keqing",
  KINICH: "kinich",
  KIRARA: "kirara",
  KLEE: "klee",
  KUJOU_SARA: "kujou_sara",
  KUKI_SHINOBU: "kuki_shinobu",
  KYRYLL_CHUDOMIROVICH_FLINS: "flins",
  LAN_YAN: "lan_yan",
  LAUMA: "lauma",
  LAYLA: "layla",
  LISA: "lisa",
  LUMINE: "lumine",
  LYNETTE: "lynette",
  LYNEY: "lyney",
  MANEKIN: "manekin",
  MANEKINA: "manekina",
  MAVUIKA: "mavuika",
  MIKA: "mika",
  MONA: "mona",
  MUALANI: "mualani",
  NAHIDA: "nahida",
  NAVIA: "navia",
  NEFER: "nefer",
  NEUVILLETTE: "neuvillette",
  NILOU: "nilou",
  NINGGUANG: "ningguang",
  NOELLE: "noelle",
  ORORON: "ororon",
  QIQI: "qiqi",
  RAIDEN_SHOGUN: "raiden_shogun",
  RAZOR: "razor",
  ROSARIA: "rosaria",
  SANGONOMIYA_KOKOMI: "sangonomiya_kokomi",
  SAYU: "sayu",
  SETHOS: "sethos",
  SHENHE: "shenhe",
  SHIKANOIN_HEIZOU: "shikanoin_heizou",
  SIGEWINNE: "sigewinne",
  SKIRK: "skirk",
  SUCROSE: "sucrose",
  TARTAGLIA: "tartaglia",
  THOMA: "thoma",
  TIGHNARI: "tighnari",
  VARESA: "varesa",
  VARKA: "varka",
  VENTI: "venti",
  WANDERER: "wanderer",
  WRIOTHESLEY: "wriothesley",
  XIANGLING: "xiangling",
  XIANYUN: "xianyun",
  XIAO: "xiao",
  XILONEN: "xilonen",
  XINGQIU: "xingqiu",
  XINYAN: "xinyan",
  YAE_MIKO: "yae_miko",
  YANFEI: "yanfei",
  YAOYAO: "yaoyao",
  YELAN: "yelan",
  YOIMIYA: "yoimiya",
  YUMEMIZUKI_MIZUKI: "yumemizuki_mizuki",
  YUN_JIN: "yun_jin",
  ZIBAI: "zibai",
  ZHONGLI: "zhongli",
} as const;
export type CharacterId = typeof CharacterIds[keyof typeof CharacterIds];

export const CharacterNames = {
  AETHER: "Итэр",
  AINO: "Айно",
  ALBEDO: "Альбедо",
  ALHAITHAM: "Аль-Хайтам",
  ALOY: "Элой",
  AMBER: "Эмбер",
  ARATAKI_ITTO: "Итто",
  ARLECCHINO: "Арлекино",
  BAIZHU: "Бай Чжу",
  BARBARA: "Барбара",
  BEIDOU: "Бэй Доу",
  BENNETT: "Беннет",
  CANDACE: "Кандакия",
  CHARLOTTE: "Шарлотта",
  CHASCA: "Часка",
  CHEVREUSE: "Шеврёз",
  CHIORI: "Тиори",
  CHONGYUN: "Чун Юнь",
  CITLALI: "Ситлали",
  CLORINDE: "Клоринда",
  COLLEI: "Коллеи",
  COLUMBINA_HYPOSELENIA: "Коломбина",
  CYNO: "Сайно",
  DAHLIA: "Далия",
  DEHYA: "Дэхья",
  DILUC: "Дилюк",
  DIONA: "Диона",
  DORI: "Дори",
  DURIN: "Дурин",
  EMILIE: "Эмилия",
  ESCOFFIER: "Эскофье",
  EULA: "Эола",
  FARUZAN: "Фарузан",
  FISCHL: "Фишль",
  FREMINET: "Фремине",
  FURINA: "Фурина",
  GAMING: "Ка Мин",
  GANYU: "Гань Юй",
  GOROU: "Горо",
  HU_TAO: "Ху Тао",
  IANSAN: "Иансан",
  IFA: "Ифа",
  ILLUGA: "Иллуги",
  INEFFA: "Инеффа",
  JAHODA: "Ягода",
  JEAN: "Джинн",
  KACHINA: "Качина",
  KAEDEHARA_KAZUHA: "Кадзуха",
  KAEYA: "Кэйа",
  KAMISATO_AYAKA: "Аяка",
  KAMISATO_AYATO: "Аято",
  KAVEH: "Кавех",
  KEQING: "Кэ Цин",
  KINICH: "Кинич",
  KIRARA: "Кирара",
  KLEE: "Кли",
  KUJOU_SARA: "Сара",
  KUKI_SHINOBU: "Синобу",
  KYRYLL_CHUDOMIROVICH_FLINS: "Флинс",
  LAN_YAN: "Лань Янь",
  LAUMA: "Лаума",
  LAYLA: "Лайла",
  LISA: "Лиза",
  LUMINE: "Люмин",
  LYNETTE: "Линетт",
  LYNEY: "Лини",
  MANEKIN: "Манекен (м)",
  MANEKINA: "Манекен (ж)",
  MAVUIKA: "Мавуика",
  MIKA: "Мика",
  MONA: "Мона",
  MUALANI: "Муалани",
  NAHIDA: "Нахида",
  NAVIA: "Навия",
  NEFER: "Нефер",
  NEUVILLETTE: "Нёвиллет",
  NILOU: "Нилу",
  NINGGUANG: "Нин Гуан",
  NOELLE: "Ноэлль",
  ORORON: "Оророн",
  QIQI: "Ци Ци",
  RAIDEN_SHOGUN: "Райдэн",
  RAZOR: "Рэйзор",
  ROSARIA: "Розария",
  SANGONOMIYA_KOKOMI: "Кокоми",
  SAYU: "Саю",
  SETHOS: "Сетос",
  SHENHE: "Шэнь Хэ",
  SHIKANOIN_HEIZOU: "Хэйдзо",
  SIGEWINNE: "Сиджвин",
  SKIRK: "Скирк",
  SUCROSE: "Сахароза",
  TARTAGLIA: "Тарталья",
  THOMA: "Тома",
  TIGHNARI: "Тигнари",
  VARESA: "Вареса",
  VARKA: "Варка",
  VENTI: "Венти",
  WANDERER: "Странник",
  WRIOTHESLEY: "Ризли",
  XIANGLING: "Сян Лин",
  XIANYUN: "Сянь Юнь",
  XIAO: "Сяо",
  XILONEN: "Шилонен",
  XINGQIU: "Син Цю",
  XINYAN: "Синь Янь",
  YAE_MIKO: "Яэ Мико",
  YANFEI: "Янь Фэй",
  YAOYAO: "Яо Яо",
  YELAN: "Е Лань",
  YOIMIYA: "Ёимия",
  YUMEMIZUKI_MIZUKI: "Мидзуки",
  YUN_JIN: "Юнь Цзинь",
  ZIBAI: "Цзы Бай",
  ZHONGLI: "Чжун Ли",
} as const;
export type CharacterName = typeof CharacterNames[keyof typeof CharacterNames];

export const TravelerIdArray = [CharacterIds.AETHER, CharacterIds.LUMINE] as const;
export type TravelerId = typeof TravelerIdArray[number];

export interface Character {
  id: CharacterId;
  name: CharacterName;
  fullName?: string;
  title: string;
  weaponText: string;
  rarity: Extract<Rarity, 4 | 5>;
  birthday: string;
  elementId: ElementId | "none";
  elementText: ElementName | "Нет";
  affiliation: string;
  region: string;
  substatText: string;
  constellation: string;
  image: string;
  version: string;
}

export type CharacterConstellations = 0 | 1 | 2 | 3 | 4 | 5 | 6;
export type CharacterListItem = Pick<Character, "id" | "name" | "rarity" | "elementId" | "elementText" | "image">;
