import type { Rarity } from "./rarities.types";

export const WeaponIds = {
  A_THOUSAND_BLAZING_SUNS: "a_thousand_blazing_suns",
  A_THOUSAND_FLOATING_DREAMS: "a_thousand_floating_dreams",
  ABSOLUTION: "absolution",
  AKUOUMARU: "akuoumaru",
  ALLEY_HUNTER: "alley_hunter",
  AMENOMA_KAGEUCHI: "amenoma_kageuchi",
  AMOS_BOW: "amos_bow",
  AQUA_SIMULACRA: "aqua_simulacra",
  AQUILA_FAVONIA: "aquila_favonia",
  ASH_GRAVEN_DRINKING_HORN: "ash_graven_drinking_horn",
  ASTRAL_VULTURES_CRIMSON_PLUMAGE: "astral_vultures_crimson_plumage",
  ATHAME_ARTIS: "athame_artis",
  AZURELIGHT: "azurelight",
  BALLAD_OF_THE_FJORDS: "ballad_of_the_fjords",
  BEACON_OF_THE_REED_SEA: "beacon_of_the_reed_sea",
  BLACK_TASSEL: "black_tassel",
  BLACKCLIFF_AGATE: "blackcliff_agate",
  BLACKCLIFF_LONGSWORD: "blackcliff_longsword",
  BLACKCLIFF_POLE: "blackcliff_pole",
  BLACKCLIFF_SLASHER: "blackcliff_slasher",
  BLACKCLIFF_WARBOW: "blackcliff_warbow",
  BLACKMARROW_LANTERN: "blackmarrow_lantern",
  BLOODSOAKED_RUINS: "bloodsoaked_ruins",
  BLOODTAINTED_GREATSWORD: "bloodtainted_greatsword",
  CALAMITY_OF_ESHU: "calamity_of_eshu",
  CALAMITY_QUELLER: "calamity_queller",
  CASHFLOW_SUPERVISION: "cashflow_supervision",
  CHAIN_BREAKER: "chain_breaker",
  CINNABAR_SPINDLE: "cinnabar_spindle",
  CLOUDFORGED: "cloudforged",
  CRANES_ECHOING_CALL: "cranes_echoing_call",
  CRIMSON_MOONS_SEMBLANCE: "crimson_moons_semblance",
  DAWNING_FROST: "dawning_frost",
  DEATHMATCH: "deathmatch",
  DIALOGUES_OF_THE_DESERT_SAGES: "dialogues_of_the_desert_sages",
  DODOCO_TALES: "dodoco_tales",
  DRAGONS_BANE: "dragons_bane",
  EARTH_SHAKER: "earth_shaker",
  ELEGY_FOR_THE_END: "elegy_for_the_end",
  ENGULFING_LIGHTNING: "engulfing_lightning",
  ETHERLIGHT_SPINDLELUTE: "etherlight_spindlelute",
  EVERLASTING_MOONGLOW: "everlasting_moonglow",
  FADING_TWILIGHT: "fading_twilight",
  FANG_OF_THE_MOUNTAIN_KING: "fang_of_the_mountain_king",
  FAVONIUS_CODEX: "favonius_codex",
  FAVONIUS_GREATSWORD: "favonius_greatsword",
  FAVONIUS_LANCE: "favonius_lance",
  FAVONIUS_SWORD: "favonius_sword",
  FAVONIUS_WARBOW: "favonius_warbow",
  FESTERING_DESIRE: "festering_desire",
  FINALE_OF_THE_DEEP: "finale_of_the_deep",
  FLAME_FORGED_INSIGHT: "flame_forged_insight",
  FLEUVE_CENDRE_FERRYMAN: "fleuve_cendre_ferryman",
  FLOWING_PURITY: "flowing_purity",
  FLUTE_OF_EZPITZAL: "flute_of_ezpitzal",
  FOOTPRINT_OF_THE_RAINBOW: "footprint_of_the_rainbow",
  FRACTURED_HALO: "fractured_halo",
  FREEDOM_SWORN: "freedom_sworn",
  GEST_OF_THE_MIGHTY_WOLF: "gest_of_the_mighty_wolf",
  HAKUSHIN_RING: "hakushin_ring",
  HAMAYUMI: "hamayumi",
  HARAN_GEPPAKU_FUTSU: "haran_geppaku_futsu",
  HARBINGER_OF_DAWN: "harbinger_of_dawn",
  HUNTERS_PATH: "hunters_path",
  IBIS_PIERCER: "ibis_piercer",
  IRON_STING: "iron_sting",
  JADEFALLS_SPLENDOR: "jadefalls_splendor",
  KAGOTSURUBE_ISSHIN: "kagotsurube_isshin",
  KAGURAS_VERITY: "kaguras_verity",
  KEY_OF_KHAJ_NISUT: "key_of_khaj_nisut",
  KITAIN_CROSS_SPEAR: "kitain_cross_spear",
  LIGHT_OF_FOLIAR_INCISION: "light_of_foliar_incision",
  LIGHTBEARING_MOONSHARD: "lightbearing_moonshard",
  LIONS_ROAR: "lions_roar",
  LITHIC_SPEAR: "lithic_spear",
  LOST_PRAYER_TO_THE_SACRED_WINDS: "lost_prayer_to_the_sacred_winds",
  LUMIDOUCE_ELEGY: "lumidouce_elegy",
  LUXURIOUS_SEA_LORD: "luxurious_sea_lord",
  MAGIC_GUIDE: "magic_guide",
  MAILED_FLOWER: "mailed_flower",
  MAKHAIRA_AQUAMARINE: "makhaira_aquamarine",
  MAPPA_MARE: "mappa_mare",
  MASTER_KEY: "master_key",
  MEMORY_OF_DUST: "memory_of_dust",
  MISSIVE_WINDSPEAR: "missive_windspear",
  MISTSPLITTER_REFORGED: "mistsplitter_reforged",
  MOONWEAVERS_DAWN: "moonweavers_dawn",
  MOUNTAIN_BRACING_BOLT: "mountain_bracing_bolt",
  NIGHTWEAVERS_LOOKING_GLASS: "nightweavers_looking_glass",
  NOCTURNES_CURTAIN_CALL: "nocturnes_curtain_call",
  OATHSWORN_EYE: "oathsworn_eye",
  PEAK_PATROL_SONG: "peak_patrol_song",
  POLAR_STAR: "polar_star",
  PREDATOR: "predator",
  PRIMORDIAL_JADE_CUTTER: "primordial_jade_cutter",
  PRIMORDIAL_JADE_WINGED_SPEAR: "primordial_jade_winged_spear",
  PROSPECTORS_DRILL: "prospectors_drill",
  PROSPECTORS_SHOVEL: "prospectors_shovel",
  PROTOTYPE_AMBER: "prototype_amber",
  PROTOTYPE_ARCHAIC: "prototype_archaic",
  PROTOTYPE_CRESCENT: "prototype_crescent",
  RAINBOW_SERPENTS_RAIN_BOW: "rainbow_serpents_rain_bow",
  RAINSLASHER: "rainslasher",
  RANGE_GAUGE: "range_gauge",
  RECURVE_BOW: "recurve_bow",
  REDHORN_STONETHRESHER: "redhorn_stonethresher",
  RELIQUARY_OF_TRUTH: "reliquary_of_truth",
  RIGHTFUL_REWARD: "rightful_reward",
  RING_OF_YAXCHE: "ring_of_yaxche",
  RUST: "rust",
  SACRIFICERS_STAFF: "sacrificers_staff",
  SACRIFICIAL_BOW: "sacrificial_bow",
  SACRIFICIAL_FRAGMENTS: "sacrificial_fragments",
  SACRIFICIAL_GREATSWORD: "sacrificial_greatsword",
  SACRIFICIAL_JADE: "sacrificial_jade",
  SACRIFICIAL_SWORD: "sacrificial_sword",
  SAPWOOD_BLADE: "sapwood_blade",
  SCION_OF_THE_BLAZING_SUN: "scion_of_the_blazing_sun",
  SEQUENCE_OF_SOLITUDE: "sequence_of_solitude",
  SERENITYS_CALL: "serenitys_call",
  SERPENT_SPINE: "serpent_spine",
  SILVERSHOWER_HEARTSTRINGS: "silvershower_heartstrings",
  SKYWARD_ATLAS: "skyward_atlas",
  SKYWARD_BLADE: "skyward_blade",
  SKYWARD_HARP: "skyward_harp",
  SKYWARD_PRIDE: "skyward_pride",
  SKYWARD_SPINE: "skyward_spine",
  SLINGSHOT: "slingshot",
  SNARE_HOOK: "snare_hook",
  SOLAR_PEARL: "solar_pearl",
  SONG_OF_BROKEN_PINES: "song_of_broken_pines",
  SONG_OF_STILLNESS: "song_of_stillness",
  SPLENDOR_OF_TRANQUIL_WATERS: "splendor_of_tranquil_waters",
  STAFF_OF_HOMA: "staff_of_homa",
  STAFF_OF_THE_SCARLET_SANDS: "staff_of_the_scarlet_sands",
  STARCALLERS_WATCH: "starcallers_watch",
  STURDY_BONE: "sturdy_bone",
  SUMMIT_SHAPER: "summit_shaper",
  SUNNY_MORNING_SLEEP_IN: "sunny_morning_sleep_in",
  SURFS_UP: "surfs_up",
  SYMPHONIST_OF_SCENTS: "symphonist_of_scents",
  TALKING_STICK: "talking_stick",
  TAMAYURATEI_NO_OHANASHI: "tamayuratei_no_ohanashi",
  THE_AlLEY_FLASH: "the_alley_flash",
  THE_BLACK_SWORD: "the_black_sword",
  THE_CATCH: "the_catch",
  THE_DAYBREAK_CHRONICLES: "the_daybreak_chronicles",
  THE_DOCKHANDS_ASSISTANT: "the_dockhands_assistant",
  THE_FIRST_GREAT_MAGIC: "the_first_great_magic",
  THE_STRINGLESS: "the_stringless",
  THE_UNFORGED: "the_unforged",
  THE_VIRIDESCENT_HUNT: "the_viridescent_hunt",
  THE_WIDSITH: "the_widsith",
  THRILLING_TALES_OF_DRAGON_SLAYERS: "thrilling_tales_of_dragon_slayers",
  THUNDERING_PULSE: "thundering_pulse",
  TIDAL_SHADOW: "tidal_shadow",
  TOME_OF_THE_ETERNAL_FLOW: "tome_of_the_eternal_flow",
  TOUKABOU_SHIGURE: "toukabou_shigure",
  TULAYTULLAHS_REMEMBRANCE: "tulaytullahs_remembrance",
  ULTIMATE_OVERLORDS_MEGA_MAGIC_SWORD: "ultimate_overlords_mega_magic_sword",
  URAKU_MISUGIRI: "uraku_misugiri",
  VERDICT: "verdict",
  VIViD_NOTIONS: "vivid_notions",
  VORTEX_VANQUISHER: "vortex_vanquisher",
  WANDERING_EVENSTAR: "wandering_evenstar",
  WAVEBREAKERS_FIN: "wavebreakers_fin",
  WAVERIDING_WHIRL: "waveriding_whirl",
  WHITE_TASSEL: "white_tassel",
  WHITEBLIND: "whiteblind",
  WINDBLUME_ODE: "windblume_ode",
  WOLF_FANG: "wolf_fang",
  WOLFS_GRAVESTONE: "wolfs_gravestone",
  XIPHOS_MOONLIGHT: "xiphos_moonlight",
} as const;
export type WeaponId = typeof WeaponIds[keyof typeof WeaponIds];

export const WeaponNames = {
  A_THOUSAND_BLAZING_SUNS: "Тысяча ослепительных солнц",
  A_THOUSAND_FLOATING_DREAMS: "Сновидения тысячи ночей",
  ABSOLUTION: "Отпущение грехов",
  AKUOUMARU: "Акуомару",
  ALLEY_HUNTER: "Охотник во тьме",
  AMENOMA_KAGEUCHI: "Амэнома Кагэути",
  AMOS_BOW: "Лук Амоса",
  AQUA_SIMULACRA: "Аква симулякрум",
  AQUILA_FAVONIA: "Меч Сокола",
  ASH_GRAVEN_DRINKING_HORN: "Пепельный рог",
  ASTRAL_VULTURES_CRIMSON_PLUMAGE: "Алое перо звёздного грифа",
  ATHAME_ARTIS: "Атаме артис",
  AZURELIGHT: "Лазурное сияние",
  BALLAD_OF_THE_FJORDS: "Баллада фьордов",
  BEACON_OF_THE_REED_SEA: "Маяк тростникового моря",
  BLACK_TASSEL: "Чёрная кисть",
  BLACKCLIFF_AGATE: "Черногорский агат",
  BLACKCLIFF_LONGSWORD: "Черногорский длинный меч",
  BLACKCLIFF_POLE: "Черногорская пика",
  BLACKCLIFF_SLASHER: "Черногорская бритва",
  BLACKCLIFF_WARBOW: "Черногорский боевой лук",
  BLACKMARROW_LANTERN: "Фонарь чёрной сердцевины",
  BLOODSOAKED_RUINS: "Окровавленные руины",
  BLOODTAINTED_GREATSWORD: "Меч драконьей крови",
  CALAMITY_OF_ESHU: "Бедствие Эшу",
  CALAMITY_QUELLER: "Усмиритель бед",
  CASHFLOW_SUPERVISION: "Казначейский надзор",
  CHAIN_BREAKER: "Разбивающий цепи",
  CINNABAR_SPINDLE: "Киноварное веретено",
  CLOUDFORGED: "Выкованный из облаков",
  CRANES_ECHOING_CALL: "Звонкий клич журавля",
  CRIMSON_MOONS_SEMBLANCE: "Очертания алой луны",
  DAWNING_FROST: "Рассветный иней",
  DEATHMATCH: "Смертельный бой",
  DIALOGUES_OF_THE_DESERT_SAGES: "Диалог пустынных мудрецов",
  DODOCO_TALES: "Истории Додоко",
  DRAGONS_BANE: "Гроза драконов",
  EARTH_SHAKER: "Сотрясающий землю",
  ELEGY_FOR_THE_END: "Элегия погибели",
  ENGULFING_LIGHTNING: "Сияющая жатва",
  ETHERLIGHT_SPINDLELUTE: "Лютня ткача света",
  EVERLASTING_MOONGLOW: "Вечное лунное сияние",
  FADING_TWILIGHT: "Гаснущие сумерки",
  FANG_OF_THE_MOUNTAIN_KING: "Клык Горного короля",
  FAVONIUS_CODEX: "Кодекс Фавония",
  FAVONIUS_GREATSWORD: "Двуручный меч Фавония",
  FAVONIUS_LANCE: "Копьё Фавония",
  FAVONIUS_SWORD: "Меч Фавония",
  FAVONIUS_WARBOW: "Боевой лук Фавония",
  FESTERING_DESIRE: "Осквернённое желание",
  FINALE_OF_THE_DEEP: "Грандиозный финал глубин",
  FLAME_FORGED_INSIGHT: "Выкованное пламенем озарение",
  FLEUVE_CENDRE_FERRYMAN: "Перевозчик Флёв Сандр",
  FLOWING_PURITY: "Сверкание чистых вод",
  FLUTE_OF_EZPITZAL: "Флейта Эспицаль",
  FOOTPRINT_OF_THE_RAINBOW: "След радуги",
  FRACTURED_HALO: "Расколотый ореол",
  FREEDOM_SWORN: "Клятва свободы",
  GEST_OF_THE_MIGHTY_WOLF: "Подвиг могучего волка",
  HAKUSHIN_RING: "Кольцо Хакусин",
  HAMAYUMI: "Хамаюми",
  HARAN_GEPPAKU_FUTSU: "Харан гэппаку фуцу",
  HARBINGER_OF_DAWN: "Предвестник зари",
  HUNTERS_PATH: "Охотничья тропа",
  IBIS_PIERCER: "Клюв ибиса",
  IRON_STING: "Стальное жало",
  JADEFALLS_SPLENDOR: "Великолепие лазурного свода",
  KAGOTSURUBE_ISSHIN: "Кагоцурубэ Иссин",
  KAGURAS_VERITY: "Истина кагура",
  KEY_OF_KHAJ_NISUT: "Ключ Хадж-нисут",
  KITAIN_CROSS_SPEAR: "Крест-копьё Китаин",
  LIGHT_OF_FOLIAR_INCISION: "Свет лиственного разреза",
  LIGHTBEARING_MOONSHARD: "Светоносный осколок луны",
  LIONS_ROAR: "Драконий рык",
  LITHIC_SPEAR: "Каменное копьё",
  LOST_PRAYER_TO_THE_SACRED_WINDS: "Молитва святым ветрам",
  LUMIDOUCE_ELEGY: "Элегия Люмидус",
  LUXURIOUS_SEA_LORD: "Благодатный владыка вод",
  MAGIC_GUIDE: "Руководство по магии",
  MAILED_FLOWER: "Цветок в латах",
  MAKHAIRA_AQUAMARINE: "Аквамарин Махайры",
  MAPPA_MARE: "Морской атлас",
  MASTER_KEY: "Мастер-ключ",
  MEMORY_OF_DUST: "Память о пыли",
  MISSIVE_WINDSPEAR: "Копьё послания ветров",
  MISTSPLITTER_REFORGED: "Рассекающий туман",
  MOONWEAVERS_DAWN: "Рассвет прядильщицы луны",
  MOUNTAIN_BRACING_BOLT: "Крепящий горы шип",
  NIGHTWEAVERS_LOOKING_GLASS: "Зеркало прядильщицы ночи",
  NOCTURNES_CURTAIN_CALL: "Вызов ноктюрна",
  OATHSWORN_EYE: "Око клятвы",
  PEAK_PATROL_SONG: "Песнь патруля пиков",
  POLAR_STAR: "Полярная звезда",
  PREDATOR: "Хищник",
  PRIMORDIAL_JADE_CUTTER: "Драгоценный омут",
  PRIMORDIAL_JADE_WINGED_SPEAR: "Нефритовый коршун",
  PROSPECTORS_DRILL: "Бур рудоискателя",
  PROSPECTORS_SHOVEL: "Лопата старателя",
  PROTOTYPE_AMBER: "Прототип: Янтарь",
  PROTOTYPE_ARCHAIC: "Прототип: Архаичный",
  PROTOTYPE_CRESCENT: "Прототип: Полумесяц",
  RAINBOW_SERPENTS_RAIN_BOW: "Струны дождя радужного змея",
  RAINSLASHER: "Дождерез",
  RANGE_GAUGE: "Дальномер",
  RECURVE_BOW: "Изогнутый лук",
  REDHORN_STONETHRESHER: "Краснорогий камнеруб",
  RELIQUARY_OF_TRUTH: "Шкатулка истин",
  RIGHTFUL_REWARD: "Справедливая награда",
  RING_OF_YAXCHE: "Кольцо Яшче",
  RUST: "Ржавый лук",
  SACRIFICERS_STAFF: "Посох жертвующей",
  SACRIFICIAL_BOW: "Церемониальный лук",
  SACRIFICIAL_FRAGMENTS: "Церемониальные мемуары",
  SACRIFICIAL_GREATSWORD: "Церемониальный двуручный меч",
  SACRIFICIAL_JADE: "Жертвенный нефрит",
  SACRIFICIAL_SWORD: "Церемониальный меч",
  SAPWOOD_BLADE: "Деревянный клинок",
  SCION_OF_THE_BLAZING_SUN: "Наследник слепящего солнца",
  SEQUENCE_OF_SOLITUDE: "Каденция одиночества",
  SERENITYS_CALL: "Зов безмятежности",
  SERPENT_SPINE: "Меч драконьей кости",
  SILVERSHOWER_HEARTSTRINGS: "Сердечные струны дождя",
  SKYWARD_ATLAS: "Небесный атлас",
  SKYWARD_BLADE: "Небесный меч",
  SKYWARD_HARP: "Небесное крыло",
  SKYWARD_PRIDE: "Небесное величие",
  SKYWARD_SPINE: "Небесная ось",
  SLINGSHOT: "Рогатка",
  SNARE_HOOK: "Крюк силка",
  SOLAR_PEARL: "Солнечная жемчужина",
  SONG_OF_BROKEN_PINES: "Песнь разбитых сосен",
  SONG_OF_STILLNESS: "Мелодия покоя",
  SPLENDOR_OF_TRANQUIL_WATERS: "Блеск тихих вод",
  STAFF_OF_HOMA: "Посох Хомы",
  STAFF_OF_THE_SCARLET_SANDS: "Посох алых песков",
  STARCALLERS_WATCH: "Бдение взывающего к звёздам",
  STURDY_BONE: "Крепкая кость",
  SUMMIT_SHAPER: "Кромсатель пиков",
  SUNNY_MORNING_SLEEP_IN: "Сон солнечным утром",
  SURFS_UP: "Лови волну",
  SYMPHONIST_OF_SCENTS: "Симфонист ароматов",
  TALKING_STICK: "Говорящая палица",
  TAMAYURATEI_NO_OHANASHI: "Тамаюратэй но оханаси",
  THE_AlLEY_FLASH: "Вспышка во тьме",
  THE_BLACK_SWORD: "Чёрный меч",
  THE_CATCH: "«Улов»",
  THE_DAYBREAK_CHRONICLES: "Хроники рассвета",
  THE_DOCKHANDS_ASSISTANT: "Верфь",
  THE_FIRST_GREAT_MAGIC: "Первый великий фокус",
  THE_STRINGLESS: "Бесструнный",
  THE_UNFORGED: "Некованый",
  THE_VIRIDESCENT_HUNT: "Зелёный лук",
  THE_WIDSITH: "Песнь странника",
  THRILLING_TALES_OF_DRAGON_SLAYERS: "Эпос о драконоборцах",
  THUNDERING_PULSE: "Громовой пульс",
  TIDAL_SHADOW: "Тень волны",
  TOME_OF_THE_ETERNAL_FLOW: "Обряд вечного течения",
  TOUKABOU_SHIGURE: "Токабо сигурэ",
  TULAYTULLAHS_REMEMBRANCE: "Воспоминания Тулайтуллы",
  ULTIMATE_OVERLORDS_MEGA_MAGIC_SWORD: "«Магический супермеч высшего владыки»",
  URAKU_MISUGIRI: "Ураку мисугири",
  VERDICT: "Вердикт",
  VIViD_NOTIONS: "Переливающиеся чаяния",
  VORTEX_VANQUISHER: "Покоритель вихря",
  WANDERING_EVENSTAR: "Скитающаяся звезда",
  WAVEBREAKERS_FIN: "Режущий волны плавник",
  WAVERIDING_WHIRL: "Вихрь на волнах",
  WHITE_TASSEL: "Белая кисть",
  WHITEBLIND: "Белая тень",
  WINDBLUME_ODE: "Ода анемонии",
  WOLF_FANG: "Волчий клык",
  WOLFS_GRAVESTONE: "Волчья погибель",
  XIPHOS_MOONLIGHT: "Лунное сияние ксифоса",
} as const;
export type WeaponName = typeof WeaponNames[keyof typeof WeaponNames];

export interface WeaponRefine {
  description: string;
  values: string[];
}

export interface Weapon {
  id: WeaponId;
  name: WeaponName;
  dupealias?: string;
  weaponText: string;
  rarity: Rarity;
  mainStatText?: string;
  effectName?: string;
  effectTemplateRaw?: string;
  r1?: WeaponRefine;
  r2?: WeaponRefine;
  r3?: WeaponRefine;
  r4?: WeaponRefine;
  r5?: WeaponRefine;
  image?: string;
  version: string;
}

export type WeaponListItem = Pick<Weapon, "id" | "name" | "rarity" | "image">;
export type WeaponR = 1 | 2 | 3 | 4 | 5;
